version: "3.9"

services:
  database:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgres/data

  app:
    depends_on:
      - database
    ports:
      - "8001:8000"
    build: ./app
    volumes:
      - ./app/:/app/
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  pgdata:
